### PR TITLE
Updated chart.js to 2.6.0 with minified js

### PR DESCRIPTION
**Pull request by crevete**
cf. #22

### CODE REVIEW

**Comment by coderbydesign** [comment]
Thanks for the PR @crevete! Just validated this locally and will update this PR once I get a new build out here shortly.

**Comment by coderbydesign** [comment]
Version 0.1.3 has been [published.](https://rubygems.org/gems/chart-js-rails/versions/0.1.3)

**Comment by crevete** [comment]
Thanks @coderbydesign !

**Comment by nubecoder** [comment]
The change to the require statement actually broke my (rails) app, this should have likely been a major version bump.
[semantic-versioning](http://guides.rubygems.org/patterns/#semantic-versioning).
Easy enough to fix, but caused a bit of confusion.

Thanks for the continued support for this gem.

**Comment by coderbydesign** [comment]
@nubecoder You're 100% right, apologies for not catching that change in the PR and versioning appropriately!

**Pull request merged**
